version: '3.8'
services:
  fastapi:
    build: ./api/.
    container_name: fastapi_app
    environment:
      - CADDY_INGRESS=api-pdf.easypanel.host
    expose:
      - "80"

  caddy:
    build: .
    container_name: caddy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
